name: "Discord Commits"
description: "GitHub Action for Discord that prints ALL commit messages."
branding:
  icon: "bell"
  color: "purple"
inputs:
  webhook:
    description: "discord webhook url without /github"
    required: true
  message:
    description: "A general message that is displayed for all commits."
  embed:
    description: "JSON string that accepts double braces for templates."

runs:
  using: "node12"
  main: "discord-commits/index.js"
