CREATE TABLE IF NOT EXISTS friendship (
	player_a UUID
		NOT NULL
		REFERENCES player (id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
			DEFERRABLE INITIALLY IMMEDIATE,

	player_b UUID
		NOT NULL
		REFERENCES player (id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
			DEFERRABLE INITIALLY IMMEDIATE,

	began TimestampTZ
		NOT NULL
		DEFAULT NOW(),

	PRIMARY KEY (player_a, player_b)
);