CREATE TABLE IF NOT EXISTS PlayerItem (
	player_id UUID
		NOT NULL
		REFERENCES player (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,
	
	item_id UUID
		NOT NULL
		REFERENCES item (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,
	
	quantity Integer
		NOT NULL
		DEFAULT 1,
	
	PRIMARY KEY (player_id, item_id)
);