CREATE TABLE IF NOT EXISTS role_assignment (
	room_id UUID
		NOT NULL
		REFERENCES room (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,
	
	player_id UUID
		NOT NULL
		REFERENCES player (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,
	
	role_name Text
		NOT NULL,
	
	FOREIGN KEY (room_id, role_name)
		REFERENCES room_role (room_id, name)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,

	PRIMARY KEY (room_id, player_id)
);