CREATE TABLE IF NOT EXISTS RoomTag (
	room_id UUID
		NOT NULL
		REFERENCES room (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,
	
	name Text
		NOT NULL,
	
	PRIMARY KEY (room_id, name)
);