CREATE TABLE IF NOT EXISTS invite (
	notification_id UUID
		NOT NULL
		PRIMARY KEY
		REFERENCES notification (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE,
	
	destination_instance_id UUID
		NOT NULL
		REFERENCES room_instance (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY IMMEDIATE
);